# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd3f2cc379f91228f6ef90850662e88e4d647c91115006c392b96977cd8edd3cf8375823adc4823e8733cb43916b69ca6657eb68d0a61cee87e8507a26d287b6

test:
  secret_key_base: 05936bef59ccb1a87b6ae997dc65dd1f0f3bead9834b568b7a83d4c7aaf6f539138eee131dd0e6afa96df8b9b3e7f2b8e3241c3de0b326da0a8073e9b9fe0919

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
